# Generated by Django 5.0.6 on 2026-09-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['returned_at', 'due_at'], name='checkout_overdue_idx'),
        ),
    ]
